### ISSUE TITLE
update gltf based examples to reflect modern gltf format

### ISSUE THREAD

**Issue by CapSparkle** [artoolkitx/jsartoolkit5#102]
Here is update in gltf standart. I see that there is no longer `position` property for `node`. As i understand there is `translation` property instead

![image](https://user-images.githubusercontent.com/25351821/100709810-52846a80-33e1-11eb-97f2-605c22db2315.png)

**Comment by NewYearCelebrate** [comment]
You have mistaken. That issue should be closed. That command is totally corresponding official docs
