### ISSUE TITLE
QUESTION: What is the Data Format of 'Data/patt.hiro'?  

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/jsartoolkit5#39]
<a href="https://github.com/uscivics"><img src="https://avatars1.githubusercontent.com/u/5046890?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [uscivics](https://github.com/uscivics)**
_Friday Sep 01, 2017 at 22:41 GMT_
_Originally opened as https://github.com/artoolkit/jsartoolkit5/issues/65_

----

I'm looking to understand the format of the Data/patt.hiro and Data/patt.kanji maker files, and how to convert in order to generate my own.  

They're included in the examples/pattern_and_barcode_threejs.html file.  

I didn't see any reference as to what format they were in, so if anyone could shed some light that would be appreciated.

Thanks.

**Comment by ThorstenBux** [comment]
See https://archive.artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training

**Comment by leyyinad** [comment]
The URL is dead. I assume this is the new one:
https://github.com/artoolkit/artoolkit-docs/blob/master/3_Marker_Training/marker_training.md
