### ISSUE TITLE
Markerless Tracking

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/jsartoolkit5#44]
<a href="https://github.com/lunzhang"><img src="https://avatars1.githubusercontent.com/u/10236369?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lunzhang](https://github.com/lunzhang)**
_Friday Nov 17, 2017 at 17:39 GMT_
_Originally opened as https://github.com/artoolkit/jsartoolkit5/issues/71_

----

Since #50 was never answered, I was wondering if its possible for marker less tracking.  The artoolkit5 can be marker-less.  [marker-less](https://archive.artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_nft_fiducial_markers)  Could the js version also be markerless?

**Comment by ThorstenBux** [comment]
@lunzhang the page you are pointing to is not marker-less just different markers. At the moment JSARToolKit and ARToolKit cannot do marker-less

**Comment by DeeCann** [comment]
The question is if jsartoolkit can track NFC, so markers borderless.
