### ISSUE TITLE
[CLOSED] [QUESTION] How to modify the default parameter of setPattRatio function? Is it related to the thickness/width of the borders of square markers?

### ISSUE THREAD

**Issue by ThorstenBux** [artoolkitx/jsartoolkit5#55]
<a href="https://github.com/Angelo8828"><img src="https://avatars1.githubusercontent.com/u/11204084?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Angelo8828](https://github.com/Angelo8828)**
_Monday Jan 08, 2018 at 07:37 GMT_
_Originally opened as https://github.com/artoolkit/jsartoolkit5/issues/80_

----

According to [this guide](https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training#marker_customizations), the arSetPattRatio is the one that can be used to modify the width of a border's marker. Is it possible to change the width of a border of a square marker using that and if possible, then how?

EDIT: I rephrased the question so that it will become much clearer

**Comment by ThorstenBux** [comment]
<a href="https://github.com/ThorstenBux"><img src="https://avatars3.githubusercontent.com/u/16772796?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ThorstenBux](https://github.com/ThorstenBux)**
_Monday Jan 08, 2018 at 08:54 GMT_

----

Have a look here: https://stackoverflow.com/questions/48143993/change-default-border-thickness-of-a-square-marker-in-artoolkit/48144740#48144740

Also look at ARToolKitX from now on as it is better maintained: https://github.com/artoolkitx/jsartoolkit5

**Comment by ThorstenBux** [comment]
In short:
It can be done using this function https://github.com/artoolkitx/jsartoolkit5/blob/master/js/artoolkit.api.js#L929

on an existing ARController object.

**Comment by ThorstenBux** [comment]
I have done the following in the past (on Android)
**10px border**
	Marker creation:
		`mk_patt --pattRatio 0.8`
```
//set marker image size
arSetPattRatio(gARHandle, 0.8);
```
***5px border**
	Configuration:
		Marker creation:
			`mk_patt --pattRatio 0.9`
```
//set marker image size
arSetPattRatio(gARHandle, 0.9);
```

The set call sets **pattern space** to 90% of the marker width

/*!
    @brief   Set the width/height of the marker pattern space, as a proportion of marker width/height.
    @details N.B. Supercedes arSetBorderSize().
    @param      handle An ARHandle referring to the current AR tracker to be modified.
    @param		pattRatio The the width/height of the marker pattern space, as a proportion of marker
        width/height. To set the default, pass AR_PATT_RATIO.
        If compatibility with ARToolKit verions 1.0 through 4.4 is required, this value
        must be 0.5.
    @result     0 if no error occured.
 */

The **pattern space** is the area within the borders. Meaning excluding borders

**Comment by Angelo8828** [comment]
Thanks again @ThorstenBux!
