### ISSUE TITLE
recurrent slowdowns on iOS

### ISSUE THREAD

**Issue by pikilipita** [artoolkitx/jsartoolkit5#65]
I am experiencing random slowdowns of the video stream on iOS ( seen on iPhone 8 ios 11.2.5).
It's pretty hard to find out what is causing the video to freeze as it is not happening all the time, just sometime. Clearing all apps on the phone and closing all other tabs on Safari does not help.

It's only the video feed that get freezed, the page itself is still running at usual framerate.

Is this a known issue with mobile Safari?

**Comment by ThorstenBux** [comment]
Thanks for your feedback. I haven't seen that so far. Let me know once you find a way to properly reproduce it, please.
I've only got an iPhone 6s here and I haven't seen any video freeze on that.
