### ISSUE TITLE
Issue with the small gyro values

### ISSUE THREAD

**Issue by siddhartpai** [artoolkitx/jsartoolkit5#67]
Hi @ThorstenBux  

I've been using jsartoolkit to create AR Experiences and it works great. Small gyro values tend to move the model slightly and this causes a jarry experience , I've noticed that this is not the same case while using AR.js(@jeromeettiene) AR.js has proper stability in the model not having a jitter when the marker is visible .  But if the camera is moved fast over the marker, AR.js doesn't remove the model from the screen when it is no longer visible. AR.js uses Artoolkit as a backend. 

What optimizations can I add on artoolkit to not consider changes in very small gyro values ?

**Comment by ThorstenBux** [comment]
You would need to have a look at @jeromeettiene 's integration of ARToolKit. And what kind of filtering he has set per default. The reason why I prefer to work with jsartoolkit5 directly is that I've got the complete control over the API and AR.js is a bit to much abstraction for my feeling.

Regarding optimizations:
- have a look at: https://github.com/artoolkitx/jsartoolkit5/blob/master/js/artoolkit.api.js#L860
the threshold mode might help depending on the environment light. 
- https://github.com/artoolkitx/jsartoolkit5/blob/master/js/artoolkit.api.js#L942 might help somethimes
- https://github.com/artoolkitx/jsartoolkit5/blob/master/js/artoolkit.api.js#L1060 another tweakable setting

Generally, I know too less about what conditions you are working in. But if you compare AR.js and jsartoolkit in the same conditions and they behave differently then you should have a deep-dive into AR.js and see what settings are adjusted.
