### ISSUE TITLE
Error: "Module._loadCamera is not a function"

### ISSUE THREAD

**Issue by sorskoot** [artoolkitx/jsartoolkit5#70]
Somehow I am missing a module that should have a function _loadCamera. Where can this be found?

I'm getting this error:
artoolkit.api.js:1646 Uncaught TypeError: Module._loadCamera is not a function
    at writeCallback (artoolkit.api.js:1646)
    at writeByteArrayToFS (artoolkit.api.js:1673)
    at XMLHttpRequest.oReq.onload (artoolkit.api.js:1689)

It points to:

function loadCamera(url, callback) {
		var filename = '/camera_param_' + camera_count++;
		var writeCallback = function() {
			var id = Module._loadCamera(filename);
			if (callback) callback(id);
		};
		if (typeof url === 'object') { // Maybe it's a byte array
			writeByteArrayToFS(filename, url, writeCallback);
		} else if (url.indexOf("\n") > -1) { // Or a string with the camera param
			writeStringToFS(filename, url, writeCallback);
		} else {
			ajax(url, filename, writeCallback);
		}
	}
```

**Comment by ThorstenBux** [comment]
@sorskoot I'm sorry, but I cannot follow you.

Can you please list the steps you perform step by step till this error occurs.

Like:

```
**Steps to reproduce:**

- 


**Expected behavior:**


**Actual behavior:**
```

**Comment by ThorstenBux** [comment]
Closing cause no response
