### ISSUE TITLE
Trying to compile with Docker: Cannot find configure

### ISSUE THREAD

**Issue by p4vv37** [artoolkitx/jsartoolkit5#71]
Hi
I've got this error while trying to compile from source, using steps from documentation:

```
docker exec emscripten2 npm run build

> jsartoolkit@0.0.0 build /src
> cd emscripten/artoolkit5/ && emconfigure ./configure && cd ../../ && node tools/makem.js; echo Built at `date`

ERROR:root:Exception thrown when invoking Popen in configure with args: "./configure"!
Traceback (most recent call last):
  File "/usr/local/bin/emconfigure", line 9, in <module>
    python_selector.run(__file__)
  File "/emsdk_portable/sdk/tools/python_selector.py", line 38, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/emsdk_portable/sdk/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/emsdk_portable/sdk/emconfigure.py", line 47, in run
    shared.Building.configure(sys.argv[1:])
  File "/emsdk_portable/sdk/tools/shared.py", line 1531, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Built at Sat May 12 05:50:03 UTC 2018
```
This looks like a reason:
`ERROR:root:Exception thrown when invoking Popen in configure with args: "./configure"!`
And right, there's only Configure, not configure. Do I do something wrong? I was hoping I'll be able to modify artoolkit a little bit to detect different types of markers.

**Comment by p4vv37** [comment]
Cloning the https://github.com/artoolkit/jsartoolkit5 instead and using described steps hepled. I guess, this repo need to be updated

**Comment by ThorstenBux** [comment]
@p4vv37 from my knowledge artoolkit/jsartoolkit5 should be an older version than this repository. I'll investigate why the Docker build fails.

**Comment by ThorstenBux** [comment]
Probably the docker version or the container that you are using is sensitive to upper/lower case you should be able to fix this with changing this file: https://github.com/artoolkitx/jsartoolkit5/blob/master/package.json#L34

**Comment by ThorstenBux** [comment]
I also updated the recommended docker image: https://github.com/artoolkitx/jsartoolkit5/commit/8f1afc5810d3f37d25215c9a1f3686dab4f5cb5f#diff-04c6e90faac2675aa89e2176d2eec7d8R30

Works perfectly for me now.

**Comment by p4vv37** [comment]
Thank you very much, I'll check it later 👍
