### ISSUE TITLE
remove a marker

### ISSUE THREAD

**Issue by pikilipita** [artoolkitx/jsartoolkit5#73]
Is it possible to remove a marker from the list of tracked marker?

I would need to dynamically load lists of markers, and clear those lists afterward

Thank you

**Comment by ThorstenBux** [comment]
Not yet, but you could do it similarly as done with add marker: https://github.com/artoolkitx/jsartoolkit5/blob/master/js/artoolkit.api.js#L1707

Let me know how you get on
