### ISSUE TITLE
NFT Branch, looking for a working demo

### ISSUE THREAD

**Issue by nicolocarpignoli** [artoolkitx/jsartoolkit5#83]
Hi everybody
I think the NFT branch is very very interesting, also for things like [AR.js](https://github.com/jeromeetienne/AR.js). I'd like to try a demo. I see there is a lot of demos on it, but I tried the 'nft_threejs.html' demo file, and I found several issues, that are blocking me:

- at some point, on `artoolkit.api.js`, there is a call to `video.src = URL.createObjectUrl(stream)`. API is old and the solution is simply to do this:  `video.srcObject = stream` instead of the above

- FS is not defined.

I have not solved the second error. It requires FS, that is a node thing. I don't understand why it is used on an HTML file, and also, how this is working in the first place.

BTW, my answer is: is there anybody that has been able to use some of the NFT branch demo with success, in the past months? Can you point me what demos to use, or another project maybe that uses such jsartoolkit branch?

thank you so much

**Comment by kalwalt** [comment]
H @nicolocarpignoli i am working to update the nft branch see this my PR  https://github.com/kalwalt/jsartoolkit5/pull/1 This is a working in progress, for now i don't receive errors but the nft image is not recognized ( or could be some other issue). 

>at some point, on artoolkit.api.js, there is a call to video.src = URL.createObjectUrl(stream). API is old and the solution is simply to do this: video.srcObject = stream instead of the above

yes the Api is a bit old, you are right but you could also try the other repository https://github.com/artoolkit/jsartoolkit5/tree/nft 


>FS is not defined.

it should be related to the last part of the artoolkit.api, 

https://github.com/artoolkitx/jsartoolkit5/blob/276e354c464e9aaad988a55964b928966a807050/js/artoolkit.api.js#L1706-L1728

and this is in my branch:

https://github.com/kalwalt/jsartoolkit5/blob/75231140af8af7eec3b65d53221dcf2b4ce59f03/js/artoolkit.api.js#L1907-L1927

Unfortunately i have also some issue with the other type of markers, i think i am very close but i can't see  where is the problem...

**Comment by nicolocarpignoli** [comment]
Great! I'm trying to run the demo, opening in a local environment https://github.com/artoolkit/jsartoolkit5/blob/nft/examples/nft_threejs.html but loading your file linked above (artoolkit.api.js).

I always get the FS is not defined error.
How do you launch examples without having this error? You launch some script/command before opening the HTML demo?

**Comment by kalwalt** [comment]
> Great! I'm trying to run the demo, opening in a local environment https://github.com/artoolkit/jsartoolkit5/blob/nft/examples/nft_threejs.html but loading your file linked above (artoolkit.api.js).
> 
> I always get the FS is not defined error.
> How do you launch examples without having this error? You launch some script/command before opening the HTML demo?

that's strange... no i don't run any script could you post all the log? but Are you trying to use my artoolkit.api.js version with the example?

**Comment by nicolocarpignoli** [comment]
Yes, I'm using your artoolkit.api.js on the HTML, but I got the same error of the 'original' artoolkit.api.js with the modifies about 'createObjectUrl' that I said on the first post. I have the latest Chrome on desktop (but error on mobile as well):

![image](https://user-images.githubusercontent.com/22395670/59928605-65022280-943f-11e9-9a8a-5e420fd5ac18.png)

Launched on a local server under https to avoid CORS and privacy problems. 
not showing camera stream as well, because the 'FS' error is blocking the app before that.

**Comment by kalwalt** [comment]
I don't know why this happens, but  what happens if you use the minified version ? and also what is the result for the `nft_init_test.html`?

**Comment by nicolocarpignoli** [comment]
For the `nft_threejs.html` I got this

![image](https://user-images.githubusercontent.com/22395670/59930774-dd6ae280-9443-11e9-96f7-d1a94fe595c9.png)


Instaed for `nft_init_test.html` I got:

![image](https://user-images.githubusercontent.com/22395670/59930805-eeb3ef00-9443-11e9-882e-0b521f4c2e73.png)


have you already seen one of these?

**Comment by kalwalt** [comment]
ok, i see that are you testing my branch. For the `nft_threejs.html` yes i receive sometimes that error, but not with the nft_threejs example. instead this is my result for the `nft_init_test.html`
![Schermata da 2019-06-21 16-59-08](https://user-images.githubusercontent.com/1275858/59931788-14da8e80-9446-11e9-8cda-b6149105543b.png) this is in my branch.

**Comment by kalwalt** [comment]
@nicolocarpignoli wait i have other changes in my branch!

**Comment by kalwalt** [comment]
@nicolocarpignoli the FS error could be caused also by a wrong compilation of the libs: the `FS` Node module i think is included by the emscripten compiler in the debug lib.

**Comment by nicolocarpignoli** [comment]
eventually will be closed by: https://github.com/artoolkitx/jsartoolkit5/pull/86

**Comment by nicolocarpignoli** [comment]
there is now! :D

**Comment by andypotato** [comment]
@nicolocarpignoli please [see here](https://github.com/artoolkitx/jsartoolkit5/issues/69#issuecomment-588053066) on how to fix the FS error
