### ISSUE TITLE
how to improve NFT market detection accuracy?

### ISSUE THREAD

**Issue by kalyanraju** [artoolkitx/jsartoolkit5#89]
Hi Awesome guys,

I really love NFT marker feature and we implemented and got great results, 

i am trying to match exact image marker. 
our marker contains 3743E on some solid background, its scanned and tracked properly, where as we have another marker 3743E-BE457 on same background, this is also getting tracked. i want to scan 100% exact match. is there a way with threshold, mode, or pattern parameters? i tried setting these from the comments in artoolkit.api.js but still its tracking 2nd marker.

Looking forward for any suggestions.

**Comment by kalwalt** [comment]
Hi @kalyanraju thanks to reporting this, first actually we have not tested NFT as multi markers in the same app, so issues may arise, and probably some changes are needed  in the C++ code to optimize the tracking and the managing of data. You are also refering to colors but NFT get imageData as BW (black-white) in the sense of gray colors. I don't know if changing the threshold may impact on the NFT detection, and same for changing the mode or pattern parameters (this last i have strong doubts for NFT)  I think that the most important factor is the quality of the marker and how many features keys/points has in it. You can test and display how many features sets has a marker with the  [dispFeatureSet](https://kalwalt.github.io/artoolkit-docs/3_Marker_Training/marker_nft_utilities.html#dispfeatureset) and to display the ImageSet with the [dispImageSet](https://kalwalt.github.io/artoolkit-docs/3_Marker_Training/marker_nft_utilities.html#dispimageset).
You can build the utilities from the [Artoolkit5](https://github.com/artoolkitx/artoolkit5) source code or you can grab the binaries of the all apps from the release [page](https://github.com/artoolkitx/artoolkit5/releases)

**Comment by kalyanraju** [comment]
Thank you
