### ISSUE TITLE
Model jittering but the image is getting tracked correctly

### ISSUE THREAD

**Issue by manojahuja11** [artoolkitx/jsartoolkit5#93]
Hi @kalwalt @nicolocarpignoli

The model is not stable. I tried it with 3 more models but the model is jittering.

https://drive.google.com/file/d/18coT2eW8Nf-H7pA0MD48GniwQT1FkGZv/view?usp=sharing

I have shared the video link with you.

And also, it only tracks the image with black background and not with white.

Thanks.

**Comment by ThorstenBux** [comment]
It is not the model.

 

Your image doesn’t have many feature points as it is too simple from a tracking perspective.

Also I assume that your dip that you set when you created the image was too low. Try 200 to see if that improves anything.

**Comment by manojahuja11** [comment]
Oh okay. I will try that. Thank you.

**Comment by kalwalt** [comment]
I agree with @ThorstenBux and you can also read [my tutorial/article](https://www.kalwaltart.com/blog/2020/02/25/tutorial-create-marker-NFT/)

**Comment by manojahuja11** [comment]
yes @ThorstenBux It works now. Thanks.
